baseURL = "/"
languageCode = "de"
title = "Digitalometer"
themesDir = "themes"
theme = "digitalometer-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Digitalometer hilft ihr Unternehmen zu digitalisieren, ohne Stellen zu schaffen. Schritt für Schritt"
    meta_og_title = "Digitaometer - Wie digital ist Ihr Unternehmen?"
    meta_og_type = "website"
    meta_og_url = "https://digitalometer.info"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Digitaometer - Wie digital ist Ihr Unternehmen?"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Test"
    url = "https://itconsense.typeform.com/to/USa1BD"
    weight = 1

[[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 2

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
